"""
Generates downloadable Excel exports:
1. SA-SAMS-ready results sheet
2. Class performance summary report
"""
from __future__ import annotations
from collections import defaultdict
from pathlib import Path

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

from app.schemas import GradedPaper, PaperStatus
from app.store import TestSession

HEADER_FILL = PatternFill(start_color="1E3A5F", end_color="1E3A5F", fill_type="solid")
HEADER_FONT = Font(color="FFFFFF", bold=True, size=11)
TITLE_FONT = Font(bold=True, size=14, color="1E3A5F")
SUBTITLE_FONT = Font(size=10, italic=True, color="555555")
THIN_BORDER = Border(
    left=Side(style="thin", color="D0D0D0"),
    right=Side(style="thin", color="D0D0D0"),
    top=Side(style="thin", color="D0D0D0"),
    bottom=Side(style="thin", color="D0D0D0"),
)
LOW_FILL = PatternFill(start_color="FDE2E2", end_color="FDE2E2", fill_type="solid")
MID_FILL = PatternFill(start_color="FFF6D8", end_color="FFF6D8", fill_type="solid")
HIGH_FILL = PatternFill(start_color="E3F5E1", end_color="E3F5E1", fill_type="solid")


def _score_fill(percentage: float | None):
    if percentage is None:
        return None
    if percentage < 40:
        return LOW_FILL
    if percentage < 60:
        return MID_FILL
    return HIGH_FILL


def _autosize(ws, widths: dict[int, int]):
    for col_idx, width in widths.items():
        ws.column_dimensions[get_column_letter(col_idx)].width = width


def build_sasams_export(session: TestSession) -> Path:
    """
    Build an Excel sheet formatted for easy import into SA-SAMS:
    Student Name | Student Number | Score | Total | Percentage | Status
    """
    wb = Workbook()
    ws = wb.active
    ws.title = "Results"

    ws.merge_cells("A1:F1")
    ws["A1"] = f"{session.subject} - {session.test_name} - Grade {session.grade}"
    ws["A1"].font = TITLE_FONT
    ws.merge_cells("A2:F2")
    ws["A2"] = f"Total marks: {session.total_marks} | Generated by MarkingAI"
    ws["A2"].font = SUBTITLE_FONT

    headers = ["Student Name", "Student Number", "Score", "Total Marks", "Percentage (%)", "Status"]
    header_row = 4
    for col, header in enumerate(headers, start=1):
        cell = ws.cell(row=header_row, column=col, value=header)
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.alignment = Alignment(horizontal="center")
        cell.border = THIN_BORDER

    class_list_by_name = {s["name"]: s.get("student_number") for s in session.class_list}

    row_idx = header_row + 1
    ordered_papers = [session.papers[pid] for pid in session.paper_order]
    ordered_papers.sort(key=lambda p: (p.matched_class_list_name or p.student_name or "zzz"))

    matched_names = set()
    for paper in ordered_papers:
        display_name = paper.matched_class_list_name or paper.student_name or "UNKNOWN - Manual review needed"
        student_number = class_list_by_name.get(paper.matched_class_list_name, "") if paper.matched_class_list_name else ""
        if paper.matched_class_list_name:
            matched_names.add(paper.matched_class_list_name)

        status_label = {
            PaperStatus.DONE: "Marked",
            PaperStatus.NEEDS_REVIEW: "Needs Review",
            PaperStatus.FAILED: "Failed - Retry",
            PaperStatus.PENDING: "Pending",
            PaperStatus.PROCESSING: "Processing",
        }.get(paper.status, str(paper.status))

        values = [
            display_name,
            student_number or "",
            paper.total_marks_awarded if paper.total_marks_awarded is not None else "",
            paper.total_marks_possible or session.total_marks,
            paper.percentage if paper.percentage is not None else "",
            status_label,
        ]
        fill = _score_fill(paper.percentage)
        for col, val in enumerate(values, start=1):
            cell = ws.cell(row=row_idx, column=col, value=val)
            cell.border = THIN_BORDER
            if col == 5 and fill:
                cell.fill = fill
            if col in (3, 4, 5):
                cell.alignment = Alignment(horizontal="center")
        row_idx += 1

    # Add students from class list who have no matched paper (absent / not found)
    for student in session.class_list:
        if student["name"] not in matched_names:
            values = [f"{student['name']} (No paper submitted)", student.get("student_number") or "",
                      "", session.total_marks, "", "Absent / Not Found"]
            for col, val in enumerate(values, start=1):
                cell = ws.cell(row=row_idx, column=col, value=val)
                cell.border = THIN_BORDER
            row_idx += 1

    _autosize(ws, {1: 32, 2: 18, 3: 10, 4: 12, 5: 15, 6: 18})
    ws.freeze_panes = f"A{header_row + 1}"

    out_path = session_export_path(session, "SASAMS_Import")
    wb.save(out_path)
    return out_path


def build_class_report(session: TestSession) -> Path:
    """Build a class performance summary: average, hardest questions, intervention list."""
    wb = Workbook()
    ws = wb.active
    ws.title = "Class Report"

    graded = [
        session.papers[pid] for pid in session.paper_order
        if session.papers[pid].status == PaperStatus.DONE and session.papers[pid].percentage is not None
    ]

    ws.merge_cells("A1:D1")
    ws["A1"] = f"Class Performance Report - {session.subject} Grade {session.grade}"
    ws["A1"].font = TITLE_FONT
    ws.merge_cells("A2:D2")
    ws["A2"] = f"{session.test_name} | Total marks: {session.total_marks} | Generated by MarkingAI"
    ws["A2"].font = SUBTITLE_FONT

    row = 4
    if graded:
        percentages = [p.percentage for p in graded]
        avg = sum(percentages) / len(percentages)
        highest = max(percentages)
        lowest = min(percentages)
    else:
        avg = highest = lowest = 0.0

    stats = [
        ("Papers marked", len(graded)),
        ("Class average", f"{avg:.1f}%"),
        ("Highest score", f"{highest:.1f}%"),
        ("Lowest score", f"{lowest:.1f}%"),
    ]
    ws.cell(row=row, column=1, value="Summary Statistics").font = Font(bold=True, size=12)
    row += 1
    for label, value in stats:
        ws.cell(row=row, column=1, value=label).font = Font(bold=True)
        ws.cell(row=row, column=2, value=value)
        row += 1

    # Hardest questions (lowest average % score per question)
    row += 2
    ws.cell(row=row, column=1, value="Hardest Questions (lowest average score)").font = Font(bold=True, size=12)
    row += 1
    headers = ["Question", "Avg Marks Awarded", "Avg Marks Possible", "Avg %"]
    for col, h in enumerate(headers, start=1):
        cell = ws.cell(row=row, column=col, value=h)
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.border = THIN_BORDER
    row += 1

    question_stats = defaultdict(lambda: {"awarded": [], "possible": []})
    for paper in graded:
        for q in paper.question_breakdown:
            question_stats[q.question]["awarded"].append(q.marks_awarded)
            if q.marks_possible:
                question_stats[q.question]["possible"].append(q.marks_possible)

    computed = []
    for question, data in question_stats.items():
        avg_awarded = sum(data["awarded"]) / len(data["awarded"]) if data["awarded"] else 0
        avg_possible = sum(data["possible"]) / len(data["possible"]) if data["possible"] else None
        avg_pct = (avg_awarded / avg_possible * 100) if avg_possible else None
        computed.append((question, avg_awarded, avg_possible, avg_pct))

    computed.sort(key=lambda x: (x[3] if x[3] is not None else 100))

    for question, avg_awarded, avg_possible, avg_pct in computed[:15]:
        values = [
            question,
            round(avg_awarded, 1),
            round(avg_possible, 1) if avg_possible else "-",
            f"{avg_pct:.0f}%" if avg_pct is not None else "-",
        ]
        fill = _score_fill(avg_pct) if avg_pct is not None else None
        for col, val in enumerate(values, start=1):
            cell = ws.cell(row=row, column=col, value=val)
            cell.border = THIN_BORDER
            if fill:
                cell.fill = fill
        row += 1

    # Intervention list: students below 40%
    row += 2
    ws.cell(row=row, column=1, value="Intervention List (below 40%)").font = Font(bold=True, size=12)
    row += 1
    headers = ["Student Name", "Score", "Percentage", "AI Comment"]
    for col, h in enumerate(headers, start=1):
        cell = ws.cell(row=row, column=col, value=h)
        cell.fill = HEADER_FILL
        cell.font = HEADER_FONT
        cell.border = THIN_BORDER
    row += 1

    at_risk = sorted(
        [p for p in graded if p.percentage is not None and p.percentage < 40],
        key=lambda p: p.percentage
    )
    if not at_risk:
        ws.cell(row=row, column=1, value="No students currently below 40% - great work!")
        row += 1
    for paper in at_risk:
        name = paper.matched_class_list_name or paper.student_name or paper.filename
        values = [name, paper.total_marks_awarded, f"{paper.percentage:.1f}%", paper.ai_comment or ""]
        for col, val in enumerate(values, start=1):
            cell = ws.cell(row=row, column=col, value=val)
            cell.border = THIN_BORDER
            cell.fill = LOW_FILL
            cell.alignment = Alignment(wrap_text=True, vertical="top")
        row += 1

    _autosize(ws, {1: 34, 2: 16, 3: 14, 4: 60})

    out_path = session_export_path(session, "Class_Report")
    wb.save(out_path)
    return out_path


def session_export_path(session: TestSession, label: str) -> Path:
    from app.config import SESSIONS_DIR
    session_dir = SESSIONS_DIR / session.session_id
    session_dir.mkdir(parents=True, exist_ok=True)
    safe_subject = "".join(c for c in session.subject if c.isalnum() or c in " _-").strip() or "Subject"
    return session_dir / f"{label}_{safe_subject}_Grade{session.grade}.xlsx"
